In [96]:
import numpy as np

In [97]:
import pandas as pd

In [98]:
data = pd.read_csv('/Users/apple/Downloads/Data-sets/students_placement.csv')
data

cgpa   iq  profile_score  placed
0    5.97  106             61       0
1    6.83  113             77       0
2    6.60  110             61       0
3    5.54  113             68       0
4    6.84  102             67       0
..    ...  ...            ...     ...
295  6.44  107             54       0
296  6.09  108             52       0
297  7.68  101             70       1
298  7.00   90             28       1
299  4.79  118             70       0

[300 rows x 4 columns]

In [99]:
data.isna().sum()

cgpa             0
iq               0
profile_score    0
placed           0
dtype: int64

In [100]:
from sklearn.preprocessing import StandardScaler

In [101]:
ss = StandardScaler()
ss

StandardScaler()

In [102]:
x = data.drop(columns=['placed'])
x

cgpa   iq  profile_score
0    5.97  106             61
1    6.83  113             77
2    6.60  110             61
3    5.54  113             68
4    6.84  102             67
..    ...  ...            ...
295  6.44  107             54
296  6.09  108             52
297  7.68  101             70
298  7.00   90             28
299  4.79  118             70

[300 rows x 3 columns]

In [103]:
x_tfd = ss.fit_transform(x)
x_tfd

array([[-0.86808798,  0.41264917,  0.06709394],
       [ 0.0185577 ,  1.25479032,  1.1892225 ],
       [-0.21856847,  0.89387268,  0.06709394],
       [-1.31141083,  1.25479032,  0.55802518],
       [ 0.02886753, -0.06857435,  0.48789215],
       [ 0.34847237, -0.54979787,  0.20736001],
       [ 0.60621821, -0.30918611,  0.76842429],
       [ 1.19387872, -1.99346842,  2.80228232],
       [-0.17732914,  1.01417856, -0.28357124],
       [ 1.03923122, -0.42949199, -0.14330517],
       [ 0.85365422, -0.06857435, -0.63423642],
       [-1.20831249,  0.41264917, -1.68623195],
       [ 0.0185577 ,  0.05173153, -2.17716319],
       [ 0.95675255, -0.79040963,  0.83855733],
       [ 1.25573773, -1.27163314, -0.42383731],
       [ 1.10109022, -1.39193902, -0.07317213],
       [-0.21856847,  1.01417856, -0.63423642],
       [ 2.08052441, -1.15132726, -1.05503463],
       [ 0.24537404, -0.67010375,  0.13722697],
       [ 0.57528871, -0.42949199,  1.1892225 ],
       [-1.06397482,  1.13448444, -0.984

In [104]:
y = data['placed']
y

0      0
1      0
2      0
3      0
4      0
      ..
295    0
296    0
297    1
298    1
299    0
Name: placed, Length: 300, dtype: int64

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
x_train,x_test,y_train,y_test = train_test_split(x_tfd,y,test_size=0.2,random_state=4)

In [107]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((240, 3), (240,), (60, 3), (60,))

In [108]:
from sklearn.metrics import accuracy_score

In [109]:
from sklearn.svm import SVC

In [110]:
svc = SVC()
svc

SVC()

In [111]:
svc.fit(x_train,y_train)

SVC()

In [112]:
y_preds = svc.predict(x_test)
y_preds

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1])

In [113]:
accuracy_score(y_test,y_preds)*100

91.66666666666666

In [114]:
svc

SVC()

In [115]:
import pickle

In [116]:
with open('model.pkl','wb') as yy:
    pickle.dump(svc,yy)

In [117]:
with open('model.pkl','rb') as jj:
    model = pickle.load(jj)

In [118]:
with open('scaler.pkl','wb') as tt:
    pickle.dump(ss,tt)

In [119]:
scaler = pickle.load(open('scaler.pkl','rb'))
scaler

StandardScaler()

In [120]:
model

SVC()

In [203]:
input_data = np.array([[3.9,39,42]]).reshape(1,-1)
input_data

array([[ 3.9, 39. , 42. ]])

In [204]:
scaled_input = scaler.transform(input_data)
scaled_input

/Users/apple/ml-setup/env/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-3.00222353, -7.64784474, -1.26543373]])

In [205]:
model.predict(scaled_input)

array([1])